### ISSUE TITLE
Query all available eligible symbols as a batch https request?

### ISSUE THREAD

**Issue by Kph1108** [aklatzke/node-iex#1]
I'm pretty new to this api and am looking for a way to query specific parameters for all of the eligible ticker symbols supported by this api. Do you know of a way? I think to start I'm looking for a list of eligible ticker symbols supported by iex and from there I want to query, for a simple example, the price of all those ticker symbols and store that data in a file.

**Comment by aklatzke** [comment]
Are you looking to fetch specific keys from the objects or just fetch the specific stock information? You can use the batch method in order to fetch multiple symbols at once: https://github.com/aklatzke/node-iex#batch-methods
